#+TITLE: Xenakis_networked_marathon

* Description (EN)

The

* Call for participation (EN)

** V1 (Kanach)
Call for Participation: Xenakis Networked Performance Marathon, December 16-17 2022 (Submission Deadline: June 15 2022)

As part of the centenary celebrations for the birth of Iannis Xenakis, the Performative Environments Arts Research Lab at the Department of Audiovisual Arts of the Ionian University, in collaboration with Athens Conservatory and Meta-Xenakis are planning a “Xenakis Networked Performance Marathon” from Friday, December 16 to Saturday, December 17, 2022. At this marathon, works that can be performed from data send via OpenSoundControl will be performed at Athens Conservatory, Athens and at the Ionian Academy, Corfu as well as other venues worldwide. The data will be shared between individual coders, performers and venues anywhere in the world, using an openly accessible server running OscGroups software (http://www.rossbencina.com/code/oscgroups). Participants are invited to submit works inspired by Iannis Xenakis' techniques or thought to be performed at this marathon. At the local venues in Athens and Corfu the works will be rendered using SuperCollider. Other SuperCollider-based environments (Tidal cycles, FoxTrot etc.) as well as independent software such as browser-based environments or applications provided by the participants will be also supported to the extent that this software can run on our local servers. The local performance group will include dancers equipped with wearable motion sensors, whose data are used locally to drive or modify sound generation, and is also relayed in real time to the remote performers using OscGroups.

Please submit your proposal by June 15, 2022 using the form provided here [link].
For more information, queries, or proposals for coordinating alternative venues, please contact Iannis Zannos at: xenakismarathon22 at gmail dot com.

** V2 (Polymeneas)

Call for Participation: Xenakis Networked Performance Marathon, December 16-17 2022 (Submission Deadline: June 15 2022)

As part of the centenary celebrations for the birth of Iannis Xenakis, the Performative Environments Arts Research Lab at the Department of Audiovisual Arts of the Ionian University, in collaboration with Athens Conservatory and Meta-Xenakis are planning a “Xenakis Networked Live Coding Marathon” from Friday, December 16 to Saturday, December 17, 2022.  At this marathon, works will be performed at the same time at Athens Conservatory (Athens), as well as other venues worldwide, using the interenet to transmit control data, audio and video and to coordinate performances between different locations. Our aim is to enable artists to perform their works from remote locations and to recreate these works in real time in Athens and other venues by running the software that creates these performances locally, based on the data received from the performers over the internet.

Performance data from live coders, scores, instrumental performers, dancers, installations and other media formats, will be shared between individual coders, performers and venues anywhere in the world live during the performances, enabling different realizations at each venue.  The main data format will be Open Sound Control (OSC), and data will be broadcast to all performing venues via OscGroups (http://www.rossbencina.com/code/oscgroups).   Additionally we will provide audio and video streaming.  At Athens Conservatory we will provide support for recreating performances on various software platforms such as SuperCollider, TidalCycles, FoxTrot, SEMA and others.

Participants are invited to submit works inspired by Iannis Xenakis' techniques or thought to be performed at this marathon, including but not limited to Live Coding performances. To give an idea of the types of projects that may be included in this global fest on Xenakis: The local performance group is designing a performance in which dancers equipped with wearable motion sensors will drive and/or modify sound with data from their movement both locally and remotely supported by OscGroups.  We invite proposals from other artists to develop and present works based on OSC and perform them concurrently in real time on various locations in the world.

* Description (EL)
