#+TITLE: Xenakis_networked_marathon

* Call for participation - Version 0

** COMMENT V1 (Kanach)
Call for Participation: Xenakis Networked Performance Marathon, December 16-17 2022 (Submission Deadline: June 15 2022)

As part of the centenary celebrations for the birth of Iannis Xenakis, the Performative Environments Arts Research Lab at the Department of Audiovisual Arts of the Ionian University, in collaboration with Athens Conservatory and Meta-Xenakis are planning a “Xenakis Networked Performance Marathon” from Friday, December 16 to Saturday, December 17, 2022. At this marathon, works that can be performed from data send via OpenSoundControl will be performed at Athens Conservatory, Athens and at the Ionian Academy, Corfu as well as other venues worldwide. The data will be shared between individual coders, performers and venues anywhere in the world, using an openly accessible server running OscGroups software (http://www.rossbencina.com/code/oscgroups). Participants are invited to submit works inspired by Iannis Xenakis' techniques or thought to be performed at this marathon. At the local venues in Athens and Corfu the works will be rendered using SuperCollider. Other SuperCollider-based environments (Tidal cycles, FoxTrot etc.) as well as independent software such as browser-based environments or applications provided by the participants will be also supported to the extent that this software can run on our local servers. The local performance group will include dancers equipped with wearable motion sensors, whose data are used locally to drive or modify sound generation, and is also relayed in real time to the remote performers using OscGroups.

Please submit your proposal by June 15, 2022 using the form provided here [link].
For more information, queries, or proposals for coordinating alternative venues, please contact Iannis Zannos at: xenakismarathon22 at gmail dot com.

** V2 (Polymeneas)

Call for Participation: Xenakis Networked Performance Marathon, December 16-17 2022 (Submission Deadline: June 15 2022)

As part of the centenary celebrations for the birth of Iannis Xenakis, the Performative Environments Arts Research Lab at the Department of Audiovisual Arts of the Ionian University, in collaboration with Athens Conservatory and Meta-Xenakis are planning a “Xenakis Networked Live Coding Marathon” from Friday, December 16 to Saturday, December 17, 2022.  At this marathon, works will be performed at the same time at Athens Conservatory (Athens), as well as other venues worldwide, using the interenet to transmit control data, audio and video and to coordinate performances between different locations. Our aim is to enable artists to perform their works from remote locations and to recreate these works in real time in Athens and other venues by running the software that creates these performances locally, based on the data received from the performers over the internet.

Performance data from live coders, scores, instrumental performers, dancers, installations and other media formats, will be shared between individual coders, performers and venues anywhere in the world live during the performances, enabling different realizations at each venue.  The main data format will be Open Sound Control (OSC), and data will be broadcast to all performing venues via OscGroups (http://www.rossbencina.com/code/oscgroups).   Additionally we will provide audio and video streaming.  At Athens Conservatory we will provide support for recreating performances on various software platforms such as SuperCollider, TidalCycles, FoxTrot, SEMA and others.

Participants are invited to submit works inspired by Iannis Xenakis' techniques or thought to be performed at this marathon, including but not limited to Live Coding performances. To give an idea of the types of projects that may be included in this global fest on Xenakis: The local performance group is designing a performance in which dancers equipped with wearable motion sensors will drive and/or modify sound with data from their movement both locally and remotely supported by OscGroups.  We invite proposals from other artists to develop and present works based on OSC and perform them concurrently in real time on various locations in the world.

* Version 1: 20 Apr 2022 10:32
** EN
As part of the centenary celebrations for the birth of Iannis Xenakis, the Performative Environments Arts Research Lab at the Department of Audiovisual Arts of the Ionian University, in collaboration with Athens Conservatory and the Meta-Xenakis  consortium are planning a “Xenakis Networked Live Coding Marathon” from Friday, December 16 to Saturday, December 17, 2022.  At this marathon, works will be performed at the same time at Athens Conservatory (Athens), as well as other venues worldwide, using the interenet to transmit control data, audio and video and to coordinate performances between different locations. Our aim is to enable artists to perform their works from remote locations and to recreate these works in real time in Athens and other venues by running the software that creates these performances locally, based on the data received from the performers over the internet.  

Performance data from live coders, scores, instrumental performers, dancers, installations and other media formats, will be shared between individual coders, performers and venues anywhere in the world live during the performances, enabling different realizations at each venue.  The main data format will be Open Sound Control (OSC), and data will be broadcast to all performing venues via OscGroups (http://www.rossbencina.com/code/oscgroups).   Additionally we will provide audio and video streaming.  At Athens Conservatory we will provide support for recreating performances on various software platforms such as SuperCollider, TidalCycles, FoxTrot, SEMA and others.

Participants are invited to submit works inspired by Iannis Xenakis' techniques or thought to be performed at this marathon, including but not limited to Live Coding performances. The local performance group is designing a performance in which dancers equipped with wearable motion sensors will drive and/or modify sound with data from their movement both locally and remotely supported by OscGroups.  We invite proposals from other artists to develop and present works based on OSC and perform them concurrently in real time on various locations in the world.

** EL

Στο πλαίσιο του εορτασμού της εκατονταετηρίδας από τη γέννηση του Iάννη Ξενάκη, το Εργαστήριο Performative Environments Arts Research Lab (PEARL) του Τμήματος Οπτικοακουστικών Τεχνών του Ιονίου Πανεπιστημίου, σε συνεργασία με το Ωδείο Αθηνών και το κονσόρτιο Meta-Xenakis προγραμματίζουν έναν μουσικοχορευτικό Μαραθώνιο, δηλαδή μια σειρά από εκτελέσεις μουσικών και χορευτικών έργων με ζωντανό κώδικα (live coding) συνολικής διάρκειας 24 ωρών, από Παρασκευή 16 Δεκεμβρίου έως το Σάββατο 17 Δεκεμβρίου 2022.
Σε αυτόν τον Μαραθώνιο, έργα θα εκτελεστούν έργα ταυτόχρονα στο Ωδείο Αθηνών (Αθήνα) και σε άλλους χώρους παγκοσμίως, χρησιμοποιώντας το διαδίκτυο για τη μετάδοση δεδομένων ελέγχου, ήχου και βίντεο και για τον συντονισμό παραστάσεων μεταξύ διαφορετικών τοποθεσιών.

Στόχος μας είναι να επιτρέψουμε στους καλλιτέχνες να εκτελέσουν τα έργα τους σε απομακρυσμένες τοποθεσίες να τα αναδημιουργήσουν σε πραγματικό χρόνο στην Αθήνα καθώς και σε άλλες τοποθεσίες, τρέχοντας το λογισμικό που δημιουργεί αυτές τις παραστάσεις επί τόπου σε κάθε τοποθεσία, με βάση τα δεδομένα που λαμβάνονται από τους ερμηνευτές μέσω του διαδικτύου. Τα δεδομένα κίνησης από χορευτές εξοπλισμένους με αισθητήρες, προγραμματιστικός κώδικας που εκτελούν οι μουσικοί κατά τη διάρκεια της παράστατη για να δημιουργήσουν ήχους, παρτιτούρες, ερμηνευτές οργάνων, χορευτές, εγκαταστάσεις και άλλες μορφές μέσων, θα διαμοιράζονται ζωντανά κατά τη διάρκεια των παραστάσεων μεταξύ ερμηνευτών και χώρων οπουδήποτε στον κόσμο. Ως πρωτόκολο για την ανταλαγή των δεδομένων θα χρησιμοποιηθεί το Open Sound Control (OSC).  Τα δεδομένα θα μεταδίδονται σε όλους τους χώρους των παραστάσεων μέσω του OscGroups (http://www.rossbencina.com/code/oscgroups). Επιπλέον, θα παρέχουμε αναμετάδοση ήχου και βίντεο όπου αυτό είναι επιθυμητό. Στο Ωδείο Αθηνών θα υποστηρίξουμε δημιουργία παραστάσεων σε διάφορες πλατφόρμες λογισμικού όπως οι SuperCollider, TidalCycles, FoxTrot, SEMA και άλλες.

Οι συμμετέχοντες καλούνται να υποβάλουν έργα εμπνευσμένα από τις τεχνικές ή τη σκέψη του Ιάννη Ξενάκη, τα οποία θα παρουσιαστούν σε αυτόν τον μαραθώνιο, συμπεριλαμβανομένων, ενδεικτικά, παραστάσεων Live Coding. Η τοπική ομάδα ερμηνείας σχεδιάζει μια παράσταση στην οποία χορευτές εξοπλισμένοι με wearable motion sensors (φορετούς αισθητήρες κίνησης) θα οδηγούν ή/και θα τροποποιούν τον ήχο με δεδομένα από την κίνησή τους, τόσο τοπικά όσο και εξ αποστάσεως, υποστηρίζόμενη από την OscGroups. Προσκαλούμε προτάσεις από άλλους καλλιτέχνες, να αναπτύξουν και να παρουσιάσουν έργα βασισμένα στο OSC και να τα εκτελέσουν ταυτόχρονα, σε πραγματικό χρόνο, σε διάφορες τοποθεσίες στον κόσμο.
* Version 2 - sent to N. Athinaios 20 Apr 2022 11:07


Αγαπητέ κύριε Αθηναίε

στη συνέχεια της συνομιλίας μας της περασμένης Δευτέρας, σας στέλνω εδώ
μια σύντομη περιγραφή της πρότασης μας για έναν παγκόσμιο μαραθώνιο εκτελέσεων
έργων με θέμα τον Γιάννη Ξενάκη.

Πιστεύω θα ήταν μια αρμόζουσα εκδήλωση για το προφίλ του Ωδείου.

Προτείνουμε η εκδήλωση αυτή να λάβει χώρα συνεχόμενα από το βράδυ της
Παρασκευής 16 Δεκεμβρίου μέχρι το βράδυ του Σαββάτου 17 Δεκεμβρίου 2022,
στο καινούργιο Black Box του Ωδείου εφόσον αυτό είναι έτοιμο. Εναλλακτικά,
θα μπορούσε να χρησιμοποιηθεί και η αίθουσα Άρης Γαρουφαλής εάν είναι ανάγκη.
Απαραίτητες προϋποθέσεις που πρέπει να παρέχονται από το Ωδείο είναι

Ευρυζωνική διασύνδεση διαδικτύου - την οποία έχετε μέσω του Εθνικού Ιδρύματος Ερευνών. Θα συνδέσουμε τους υπολογιστές μας στο διαδίκτυο μέσω Εthernet. Απότι έμαθα παρέχονται πρίζες ethernet στο Black Box όσο και στην αίθουσα Άρης Γαρουφαλής
Ηχεία υψηλής πιστότητας για την αναμετάδοση του ήχου.  Ηχεία του τύπου που υπάρχουν ήδη στο νέο Αμφιθέατρο του Ωδείου είναι κατάλληλα. Στην ανάγκη μπορούμε να νοικιάσουμε εμείς ηχεία - αλλά αυτό αποτελεί μόνο λύση εφεδρική.

Η ομάδα υποστήριξης από το Τμήμα Τεχνών Ήχου και Εικόνας του Ιονίου Πανεπιστήμίου
θα παρέχει τους απαιτούμενους υπολογιστές και την τεχνική υποστήριξη τόσο από
πλευράς λογισμικού όσο και από πλευράς διασύνδεσης στο Διαδίκτυο.

Παρακάτω επισυνάπτεται περιγραφή του πρότζεκτ στα αγγλικά και στα ελληνικά.
Παραμένω στη διάθεση σας για κάθε επεξήγηση.

Με εκτίμηση,

Γιάννης Ζάννος


* English

As part of the centenary celebrations for the birth of Iannis Xenakis, the Performative Environments Arts Research Lab at the Department of Audiovisual Arts of the Ionian University, in collaboration with Athens Conservatory and the Meta-Xenakis  consortium are planning a “Xenakis Networked Performance Marathon” from Friday, December 16 to Saturday, December 17, 2022.  At this marathon, works will be performed at the same time at Athens Conservatory (Athens), as well as other venues worldwide, using the interenet to transmit control data, audio and video and to coordinate performances between different locations. Our aim is to enable artists to perform their works from remote locations and to recreate these works in real time in Athens and other venues by running the software that creates these performances locally, based on the data received from the performers over the internet.  

Performance data from live coders, scores, instrumental performers, dancers, installations and other media formats, will be shared between individual coders, performers and venues anywhere in the world live during the performances, enabling different realizations at each venue.  The main data format will be Open Sound Control (OSC), and data will be broadcast to all performing venues via OscGroups (http://www.rossbencina.com/code/oscgroups).   Additionally we will provide audio and video streaming.  At Athens Conservatory we will provide support for recreating performances on various software platforms such as SuperCollider, TidalCycles, FoxDot, SEMA and others.

Participants are invited to submit works inspired by Iannis Xenakis' techniques or thought to be performed at this marathon, including but not limited to Live Coding performances. The local performance group is designing a performance in which dancers equipped with wearable motion sensors will drive and/or modify sound with data from their movement both locally and remotely supported by OscGroups.  We invite proposals from other artists to develop and present works based on OSC and perform them concurrently in real time on various locations in the world.

* Ελληνικά

Στο πλαίσιο του εορτασμού της εκατονταετηρίδας από τη γέννηση του Iάννη Ξενάκη, το Εργαστήριο Performative Environments Arts Research Lab (PEARL) του Τμήματος Οπτικοακουστικών Τεχνών του Ιονίου Πανεπιστημίου, σε συνεργασία με το Ωδείο Αθηνών και το κονσόρτιο Meta-Xenakis προγραμματίζουν έναν μουσικοχορευτικό Μαραθώνιο, δηλαδή μια σειρά από εκτελέσεις μουσικών και χορευτικών έργων με ζωντανό κώδικα (live coding) συνολικής διάρκειας 24 ωρών, από Παρασκευή 16 Δεκεμβρίου έως το Σάββατο 17 Δεκεμβρίου 2022. Σε αυτόν τον Μαραθώνιο, θα εκτελεστούν έργα ταυτόχρονα στο Ωδείο Αθηνών (Αθήνα) και σε άλλους χώρους παγκοσμίως, χρησιμοποιώντας το διαδίκτυο για τη μετάδοση δεδομένων ελέγχου, ήχου και βίντεο και για τον συντονισμό παραστάσεων μεταξύ διαφορετικών τοποθεσιών.

Στόχος μας είναι να επιτρέψουμε στους καλλιτέχνες να εκτελέσουν τα έργα τους σε απομακρυσμένες τοποθεσίες να τα αναδημιουργήσουν σε πραγματικό χρόνο στην Αθήνα καθώς και σε άλλες τοποθεσίες, τρέχοντας το λογισμικό που δημιουργεί αυτές τις παραστάσεις επί τόπου σε κάθε τοποθεσία, με βάση τα δεδομένα που λαμβάνονται από τους ερμηνευτές μέσω του διαδικτύου. Τα δεδομένα κίνησης από χορευτές εξοπλισμένους με αισθητήρες, προγραμματιστικός κώδικας που εκτελούν οι μουσικοί κατά τη διάρκεια της παράστατη για να δημιουργήσουν ήχους, παρτιτούρες, ερμηνευτές οργάνων, χορευτές, εγκαταστάσεις και άλλες μορφές μέσων, θα διαμοιράζονται ζωντανά κατά τη διάρκεια των παραστάσεων μεταξύ ερμηνευτών και χώρων οπουδήποτε στον κόσμο. Ως πρωτόκολο για την ανταλαγή των δεδομένων θα χρησιμοποιηθεί το Open Sound Control (OSC).  Τα δεδομένα θα μεταδίδονται σε όλους τους χώρους των παραστάσεων μέσω του OscGroups (http://www.rossbencina.com/code/oscgroups). Επιπλέον, θα παρέχουμε αναμετάδοση ήχου και βίντεο όπου αυτό είναι επιθυμητό. Στο Ωδείο Αθηνών θα υποστηρίξουμε δημιουργία παραστάσεων σε διάφορες πλατφόρμες λογισμικού όπως οι SuperCollider, TidalCycles, FoxDot, SEMA και άλλες.

Οι συμμετέχοντες καλούνται να υποβάλουν έργα εμπνευσμένα από τις τεχνικές ή τη σκέψη του Ιάννη Ξενάκη, τα οποία θα παρουσιαστούν σε αυτόν τον Μαραθώνιο, συμπεριλαμβανομένων, ενδεικτικά, παραστάσεων Live Coding. Η τοπική ομάδα ερμηνείας σχεδιάζει μια παράσταση στην οποία χορευτές εξοπλισμένοι με wearable motion sensors (φορετούς αισθητήρες κίνησης) θα οδηγούν ή/και θα τροποποιούν τον ήχο με δεδομένα από την κίνησή τους, τόσο τοπικά όσο και εξ αποστάσεως, υποστηρίζόμενη από την OscGroups. Προσκαλούμε προτάσεις από άλλους καλλιτέχνες, να αναπτύξουν και     να παρουσιάσουν έργα βασισμένα στο OSC και να τα εκτελέσουν ταυτόχρονα, σε πραγματικό χρόνο, σε διάφορες τοποθεσίες στον κόσμο.
