#+TITLE: About Pearl_text Drafts

To be started by 29.3.2022.

* Short Description for landing Page

** Background Notes  / Links

Between technology and society.

"Mediated": What is "mediated"? What is a "medium".  Technical medium / Non-technical medium ???

Society:
https://en.wikipedia.org/wiki/Performativity

Technology-Society
https://en.wikipedia.org/wiki/Interaction_design

Environment: Human/Social Environment, Natural Environment, Technical Environment.
Technical environment as the medium between human and natural environment?

Can an environment or a social group be performative?

Jan Assmann and John Czaplicka: Collective Memory and Cultural Identity. New German Critique No. 65, Cultural History/Cultural Studies (Spring - Summer, 1995), pp. 125-133. Duke University Press

https://www.jstor.org/stable/488538

- Medium and Writing (Medium, Writing, Tool).
- Embodiment: Can the body be Medium, Tool and Writing System?  Traditional cultures with emphasis in orality.

  https://chs.harvard.edu/book/nagy-gregory-comparative-studies-in-greek-and-indic-meter/


* Longer Description

* Bibliography - Links

This is for long term discussion. But it helps to start collecting now. ;-)
